version: "3.8"
services: 
    app:
        build: 
            context: .
        volumes: 
            - .:/core
        ports: 
            - 3000:3000
        image: simonmathelela/pokedexfrontend
        container_name: pokedex
        command: npm start